version: 2.1
jobs:
  build-and-deploy-firebase:
    docker:
      - image: node:18.4.0-alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install 
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build application for production
          command: yarn build
      - run:
          name: Install firebase tools
          command: npm install -g firebase-tools   
      # - run:
      #     name: Deploy app to Firebase
      #     command: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy-firebase:
          filters:
            branches:
              only:
                - develop
                - devops/*