version: 2.1
jobs:
  build-and-deploy-firebase:
    docker:
      - image: node:18.4.0-alpine
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install 
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build application for production
          command: yarn build
      - run:
          name: Install firebase tools
          command: npm install -g firebase-tools
      # Deploy application on development server, when branch name === develop
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - run: 
                name: "Deploy application to dev.oswrecruitment.com"
                command: firebase deploy --token=$FIREBASE_TOKEN -P dev
      # Deploy application on staging server, when branch name === stage
      - when:
          condition:
            equal: [ stage, << pipeline.git.branch >> ]
          steps:
            - run: 
                name: "Deploy application to stage.oswrecruitment.com"
                command: firebase deploy --token=$FIREBASE_TOKEN -P stage
      # Deploy application on production server, when branch name === release
      - when:
          condition:
            equal: [ release, << pipeline.git.branch >> ]
          steps:
            - run: 
                name: "Deploy application to oswrecruitment.com"
                command: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy-firebase